# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dimos/teleop/pico/proto/tracking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dimos/teleop/pico/proto/tracking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&dimos/teleop/pico/proto/tracking.proto\x12\x0cPXREAService\x1a\x1bgoogle/protobuf/empty.proto\"\x14\n\x05VRPid\x12\x0b\n\x03pid\x18\x01 \x01(\x05\"-\n\x0c\x44\x65viceStatus\x12\r\n\x05\x64\x65vid\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\"3\n\x0f\x44\x65viceStateJson\x12\r\n\x05\x64\x65vid\x18\x01 \x01(\t\x12\x11\n\tstatejson\x18\x02 \x01(\t\"\xaa\x01\n\x0eServerFeedback\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x05\x64\x65vid\x18\x03 \x01(\tH\x00\x12/\n\tdevstatus\x18\x05 \x01(\x0b\x32\x1a.PXREAService.DeviceStatusH\x00\x12\x38\n\x0f\x64\x65vicestatejson\x18\x0f \x01(\x0b\x32\x1d.PXREAService.DeviceStateJsonH\x00\x42\x0e\n\x0c\x46\x65\x65\x64\x62\x61\x63kArgs2\xd8\x01\n\tEAService\x12J\n\x13WatchServerFeedback\x12\x13.PXREAService.VRPid\x1a\x1c.PXREAService.ServerFeedback0\x01\x12\x43\n\x14\x43\x61ncelServerFeedback\x12\x13.PXREAService.VRPid\x1a\x16.google.protobuf.Empty\x12:\n\x08SendBeat\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dimos.teleop.pico.proto.tracking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VRPID']._serialized_start=85
  _globals['_VRPID']._serialized_end=105
  _globals['_DEVICESTATUS']._serialized_start=107
  _globals['_DEVICESTATUS']._serialized_end=152
  _globals['_DEVICESTATEJSON']._serialized_start=154
  _globals['_DEVICESTATEJSON']._serialized_end=205
  _globals['_SERVERFEEDBACK']._serialized_start=208
  _globals['_SERVERFEEDBACK']._serialized_end=378
  _globals['_EASERVICE']._serialized_start=381
  _globals['_EASERVICE']._serialized_end=597
# @@protoc_insertion_point(module_scope)
